### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by superrnovae** [23Aaron/Betelguese#11]
What exactly does this error mean?   

Output:
`
Downloading…   
Downloading Resources...   
Copying Files to your device   
Installing Procursus bootstrap and Sileo on your device   
tar: ./usr/bin/chflags: Cannot open: File exists   
/dev/stdin: line 202: 33000 Terminated: 15             
iproxy 42264 44 >> /dev/null 2> /dev/null  (wd: /private/var/folders/mp/hq044wr10694m52j93y6v9lh0000gn/T/betelguese)
Error 2
`
   
**Device:** iPad Air 2 Wi-Fi
**iPadOS:** 14.5.1

**Comment by maximebories** [comment]
Same problem here, errors as soon as the files are transferred on the device.

`#######00.0%Copying Files to your device
Installing Procursus bootstrap and Sileo on your device
tar: ./usr/bin/tee: Cannot open: File exists
tar: ./usr/bin/md5sum: Cannot open: File exists
tar: ./usr/bin/split: Cannot open: File exists
tar: ./usr/bin/run-parts: Cannot open: File exists
tar: ./usr/bin/cfversion: Cannot open: File exists
tar: ./usr/bin/pathchk: Cannot open: File exists
tar: ./usr/bin/runcon: Cannot open: File exists
tar: ./usr/bin/expand: Cannot open: File exists
tar: ./usr/bin/tty: Cannot open: File exists
tar: ./usr/bin/basename: Cannot open: File exists
tar: ./usr/bin/install: Cannot open: File exists
tar: ./usr/bin/dpkg-statoverride: Cannot open: File exists
tar: ./usr/bin/echo: Cannot open: File exists
tar: ./usr/bin/sudoedit: Cannot create symlink to ‘sudo’: File exists
tar: ./usr/bin/du: Cannot open: File exists
tar: ./usr/bin/dpkg-deb: Cannot open: File exists
tar: ./usr/bin/diff3: Cannot open: File exists`

For me it goes on for about 1300 lines, recursively for every binaries on target. Until finally 

`/dev/stdin: line 202: 12739 Terminated: 15          iproxy 42264 44 >> /dev/null 2> /dev/null  (wd: /private/var/folders/6z/bd_g805s579fx65_myml56tr0000gn/T/betelguese)

Error 2`

<img width="752" alt="Screen Shot 2021-05-13 at 21 35 34" src="https://user-images.githubusercontent.com/30550722/118178124-dda76900-b433-11eb-977b-11c465a9f838.png">

Full log available if needs be.

I'm on iPhone 7 iOS 14.5.1

**Comment by yougotwill** [comment]
Similar issue. I was doing a rejailbreak without restoring first. This might be relevant. https://www.reddit.com/r/jailbreak/comments/kposal/question_rejailbreaking_on_odysseyra1n_question/ghz209j/

Will try and restore and do a fresh jailbreak and see what happens.

**Comment by yougotwill** [comment]
Confirmed the issue. Basically once you have jailbroken with checkra1n and then installed odysseyra1n with Betelgeuse if you ever have to re-jailbreak (phone ran out of battery etc.) you should only run checkra1n again and **not** Betelgeuse.

Maybe Betelgeuse should give a more descriptive message to say that odysseyra1n has already been installed and only checkra1n is required for re-jailbreaking?

**Comment by 23Aaron** [comment]
Yep, @yougotwill got it right. This is only to install the necessary files on first jailbreak/after restore.

Subsequent jailbreaks only need the checkra1n app.

Will likely add a notice about this in an update to the app.
