### ISSUE TITLE
Betelgeuse not detecting device

### ISSUE THREAD

**Issue by dinouse** [23Aaron/Betelguese#12]
I have iPhone SE 2016 after jailbreaking and as soon i want to odysseyra1n the tools doesnt seems to detecting my device but checkra1n do detecting my device. 

Bigsur 11.3.1
iPhone SE 2016 iOS 14.0

**Comment by StateOfInstinct** [comment]
Same with me 

Big Sur 11.4
iPhone 7 iOS 14.4

**Comment by 23Aaron** [comment]
Have you taken the usual troubleshooting steps? Unplugging and replugging the device in etc.

**Comment by StateOfInstinct** [comment]
Yes, I have

**Comment by ZydePunk77** [comment]
Same. Will not recognize iPhone 7, but will recognize my X that’s jailbroken with Taurine

**Comment by 23Aaron** [comment]
@ZydePunk77 Are both devices plugged in?

**Comment by ZydePunk77** [comment]
> @ZydePunk77 Are both devices plugged in?

No. They were not. It recognizes the X....but acts as if nothing is connected when I plug in my iPhone 7. 

I’ve never had them both plugged in simultaneously.

**Comment by kirb** [comment]
Closing due to time elapsed since the issue was opened. If the issue is still occurring, please feel free to reopen or make a new issue.
