### ISSUE TITLE
Abcdefg

### ISSUE THREAD

**Issue by Zaq14rfv** [23Aaron/Betelguese#2]
if the repo reaches 30 forks, 30 watchers and 75 stars by the end of today, $10 tweak giveaway!

it reached,where is the money?

**Comment by BenSova** [comment]
It's not though.

![image](https://user-images.githubusercontent.com/65474198/112326990-a9f16380-8c7a-11eb-97e0-de9cf52bf6d8.jpeg)

**Comment by 23Aaron** [comment]
It didn't meet the goal in time, but I'll still be doing the giveaway anyway. 

It'll be on https://discord.gg/sileo
