### ISSUE TITLE
Error 134

### ISSUE THREAD

**Issue by sunilj0hn** [23Aaron/Betelguese#4]
What does it mean?

**Comment by NguyenAnhHD** [comment]
same here, not work for me :(

**Comment by kirb** [comment]
Does this still happen with version 1.1?

**Comment by alegye** [comment]
<img width="509" alt="Captura de Pantalla 2021-04-30 a la(s) 7 03 23 p  m" src="https://user-images.githubusercontent.com/14081671/116764610-4aa81100-a9e7-11eb-8b61-9edea4ff891f.png">                                I can't install ios 14.5 jailbreak error 1 con la  version 1.1

**Comment by ghost** [comment]
That's error "1" and this issue is for error "134", and it clearly says what to do inside the popup.

**Comment by 23Aaron** [comment]
This should be fixed in 1.1.

Closing.
