### ISSUE TITLE
Implement libimobiledevice's idevicepair.

### ISSUE THREAD

**Issue by m1stadev** [23Aaron/Betelguese#5]
Implementing idevicepair from libimobiledevice would get rid of Error 1, since it'd force a device to pair with your computer (unless it isn't connected at all).

**Comment by milkly1235writer** [comment]
Use

**Comment by kirb** [comment]
Implemented in 1.1 by using MobileDevice.framework directly (no real need to add a dependency to libimd unless we were making this cross-platform).
