### ISSUE TITLE
I can't install ios 14.5 jailbreak Error 1

### ISSUE THREAD

**Issue by alegye** [23Aaron/Betelguese#9]
![](https://user-images.githubusercontent.com/14081671/116764610-4aa81100-a9e7-11eb-8b61-9edea4ff891f.png)

I can't install ios 14.5 jailbreak Error 1 with version 1.1

**Comment by ghost** [comment]
What happens if you do what it says?

**Comment by alegye** [comment]
sorry friend what happens ask wrong and I put another time I have the problem that I can not install in ios 14.5 gives me error Error 1 version 1.1

**Comment by 23Aaron** [comment]
User has a 3rd Generation iPad Pro which isn't compatible. Closing.
